.PHONY: help up down logs sync sync-ml backend migrate migration lint typecheck test check docs-check frontend frontend-build frontend-lint ios-build ios-test ios-typecheck ios-fixtures

help:
	@echo "Infra (docker compose: postgres, pgadmin, frontend dev server)"
	@echo "  make up             start postgres, pgadmin, frontend"
	@echo "  make down           stop them"
	@echo "  make logs           tail docker compose logs"
	@echo ""
	@echo "Backend (native uv -- mlx-embeddings needs Apple Silicon, can't run in the docker containers)"
	@echo "  make sync           install backend deps (main + dev group)"
	@echo "  make sync-ml        also install the offline pipeline's ML libraries (torch, transformers, ...)"
	@echo "  make backend        run the API with --reload"
	@echo "  make migrate        apply alembic migrations"
	@echo "  make migration m=\"...\"  new autogenerated migration"
	@echo "  make lint           ruff check app/"
	@echo "  make typecheck      pyright"
	@echo "  make test           pytest (backend/tests/ only, see docs/engineering/testing.md)"
	@echo "  make check          lint + typecheck + test + docs-check, same order as CI"
	@echo "  make docs-check     assert the counts docs quote still match the repo"
	@echo ""
	@echo "iOS (native SwiftUI client, see ios/AGENTS.md)"
	@echo "  make ios-build      build LudoraKit (no Xcode needed)"
	@echo "  make ios-test       run the decoding + query tests"
	@echo "  make ios-typecheck  typecheck the SwiftUI sources against the iOS SDK"
	@echo "  make ios-fixtures   re-capture test fixtures from a running backend"
	@echo ""
	@echo "Frontend (runs inside the docker container -- no host node/npm, see frontend/AGENTS.md)"
	@echo "  make frontend       start just the frontend dev server"
	@echo "  make frontend-build npm run build (strict tsc) inside the container"
	@echo "  make frontend-lint  npm run lint (oxlint) inside the container"

## Infra

up:
	docker compose up -d

down:
	docker compose down

logs:
	docker compose logs -f

## Backend

sync:
	cd backend && uv sync

sync-ml:
	cd backend && uv sync --group ml

backend:
	cd backend && uv run uvicorn app.main:app --reload

migrate:
	cd backend && uv run alembic upgrade head

migration:
	cd backend && uv run alembic revision --autogenerate -m "$(m)"

lint:
	cd backend && uv run ruff check app/

typecheck:
	cd backend && uv run pyright

test:
	cd backend && uv run pytest

# Docs quote counts that are derivable (migrations, pipeline scripts, REST
# endpoints). They went stale silently once, so they are checked rather than
# tracked by hand. Stdlib only, no backend deps, no running server.
docs-check:
	@python3 scripts/tools/check_docs.py

# Same order as .github/workflows/backend-ci.yml: ruff -> pyright -> pytest,
# then the docs check.
check: lint typecheck test docs-check

## Frontend

frontend:
	docker compose up -d frontend

frontend-build:
	docker compose exec frontend npm run build

frontend-lint:
	docker compose exec frontend npm run lint

## iOS

# LudoraKit imports only Foundation, so it builds and tests on the Mac with
# no Xcode project and no simulator runtime. The app target is built from
# Xcode; see ios/README.md.
ios-build:
	cd ios/LudoraKit && swift build

ios-test:
	cd ios/LudoraKit && swift test

# The SwiftUI sources cannot be built by SwiftPM (they are an app target,
# not a package), but they can still be typechecked against the iOS SDK,
# which is enough to catch a break without opening Xcode.
ios-typecheck:
	@SDK=$$(xcrun --sdk iphonesimulator --show-sdk-path); \
	rm -rf /tmp/ludora-kit-ios && \
	xcrun swiftc -sdk "$$SDK" -target arm64-apple-ios17.0-simulator \
		-emit-module -emit-module-path /tmp/ludora-kit-ios/LudoraKit.swiftmodule \
		-module-name LudoraKit $$(find ios/LudoraKit/Sources -name "*.swift") && \
	xcrun swiftc -sdk "$$SDK" -target arm64-apple-ios17.0-simulator \
		-I /tmp/ludora-kit-ios -typecheck $$(find ios/Ludora -name "*.swift") && \
	echo "ios: typecheck clean"

# Fixtures are captured from a live backend, never hand-written: they are
# what makes a backend shape change fail an iOS test. Needs `make up` and
# `make backend` running first.
ios-fixtures:
	@bash scripts/capture_ios_fixtures.sh
