.PHONY: help up down logs sync sync-ml backend migrate migration lint typecheck test check frontend frontend-build frontend-lint observability-up observability-down observability-logs

help:
	@echo "Infra (docker compose: postgres, pgadmin, frontend dev server)"
	@echo "  make up             start postgres, pgadmin, frontend"
	@echo "  make down           stop them"
	@echo "  make logs           tail docker compose logs"
	@echo ""
	@echo "Observability (opt-in, off by default -- see observability/README.md)"
	@echo "  make observability-up    start otel-collector, prometheus, loki, tempo, grafana"
	@echo "  make observability-down  stop them"
	@echo "  make observability-logs  tail their logs"
	@echo ""
	@echo "Backend (native uv -- mlx-embeddings needs Apple Silicon, can't run in the docker containers)"
	@echo "  make sync           install backend deps (main + dev group)"
	@echo "  make sync-ml        also install the offline pipeline's ML libraries (torch, transformers, ...)"
	@echo "  make backend        run the API with --reload"
	@echo "  make migrate        apply alembic migrations"
	@echo "  make migration m=\"...\"  new autogenerated migration"
	@echo "  make lint           ruff check app/"
	@echo "  make typecheck      pyright"
	@echo "  make test           pytest (backend/tests/ only, see docs/engineering/testing.md)"
	@echo "  make check          lint + typecheck + test, same order as CI"
	@echo ""
	@echo "Frontend (runs inside the docker container -- no host node/npm, see frontend/AGENTS.md)"
	@echo "  make frontend       start just the frontend dev server"
	@echo "  make frontend-build npm run build (strict tsc) inside the container"
	@echo "  make frontend-lint  npm run lint (oxlint) inside the container"

## Infra

up:
	docker compose up -d

down:
	docker compose down

logs:
	docker compose logs -f

## Observability (opt-in)

observability-up:
	docker compose --profile observability up -d otel-collector prometheus loki tempo grafana

observability-down:
	docker compose --profile observability down

observability-logs:
	docker compose --profile observability logs -f otel-collector prometheus loki tempo grafana

## Backend

sync:
	cd backend && uv sync

sync-ml:
	cd backend && uv sync --group ml

backend:
	cd backend && uv run uvicorn app.main:app --reload

migrate:
	cd backend && uv run alembic upgrade head

migration:
	cd backend && uv run alembic revision --autogenerate -m "$(m)"

lint:
	cd backend && uv run ruff check app/

typecheck:
	cd backend && uv run pyright

test:
	cd backend && uv run pytest

# Same order as .github/workflows/backend-ci.yml: ruff -> pyright -> pytest.
check: lint typecheck test

## Frontend

frontend:
	docker compose up -d frontend

frontend-build:
	docker compose exec frontend npm run build

frontend-lint:
	docker compose exec frontend npm run lint
