"""Add normalized relational entities

Revision ID: 00e27df745ad
Revises: faa4df3d84fb
Create Date: 2026-08-15 05:49:04.676357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e27df745ad'
down_revision: Union[str, Sequence[str], None] = 'faa4df3d84fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('designers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designers_name'), 'designers', ['name'], unique=True)
    op.create_table('mechanics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechanics_name'), 'mechanics', ['name'], unique=True)
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishers_name'), 'publishers', ['name'], unique=True)
    op.create_table('game_categories',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.bgg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'category_id')
    )
    op.create_table('game_designers',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('designer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['designer_id'], ['designers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.bgg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'designer_id')
    )
    op.create_table('game_mechanics',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('mechanic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.bgg_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'mechanic_id')
    )
    op.create_table('game_publishers',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.bgg_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'publisher_id')
    )
    op.alter_column('games', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('games', 'categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('categories', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('games', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_table('game_publishers')
    op.drop_table('game_mechanics')
    op.drop_table('game_designers')
    op.drop_table('game_categories')
    op.drop_index(op.f('ix_publishers_name'), table_name='publishers')
    op.drop_table('publishers')
    op.drop_index(op.f('ix_mechanics_name'), table_name='mechanics')
    op.drop_table('mechanics')
    op.drop_index(op.f('ix_designers_name'), table_name='designers')
    op.drop_table('designers')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
