"""Add rating distribution

Revision ID: 04b1ebff26d4
Revises: f7d3776dc81e
Create Date: 2026-08-15 16:14:43.307527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b1ebff26d4'
down_revision: Union[str, Sequence[str], None] = 'f7d3776dc81e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('num_ratings', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('rating_distribution', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'rating_distribution')
    op.drop_column('games', 'num_ratings')
    # ### end Alembic commands ###
