"""Add vector and search columns

Revision ID: 2388b93dabc8
Revises: f998ed3df8b5
Create Date: 2026-08-15 14:20:25.155813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2388b93dabc8'
down_revision: Union[str, Sequence[str], None] = 'f998ed3df8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('games', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('games', sa.Column('embedding_model', sa.String(), nullable=True))
    op.add_column('games', sa.Column('embedding_updated_at', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'search_vector')
    op.drop_column('games', 'embedding_updated_at')
    op.drop_column('games', 'embedding_model')
    op.drop_column('games', 'embedding')
    # ### end Alembic commands ###
