"""Add category ranks

Revision ID: 462f9d4f4b62
Revises: 04b1ebff26d4
Create Date: 2026-08-15 16:40:47.413029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462f9d4f4b62'
down_revision: Union[str, Sequence[str], None] = '04b1ebff26d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('category_ranks', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'category_ranks')
    # ### end Alembic commands ###
