"""add rank and family

Revision ID: 875574550d3c
Revises: c68cea7e830d
Create Date: 2026-08-15 03:27:56.628957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875574550d3c'
down_revision: Union[str, Sequence[str], None] = 'c68cea7e830d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('family', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'family')
    op.drop_column('games', 'rank')
    # ### end Alembic commands ###
