"""Add ABSA tables

Revision ID: de5ab409f353
Revises: f52e87b1f96c
Create Date: 2026-08-15 21:34:10.858512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5ab409f353'
down_revision: Union[str, Sequence[str], None] = 'f52e87b1f96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_aspect_aggregates',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('aspect', sa.String(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=True),
    sa.Column('negative_count', sa.Integer(), nullable=True),
    sa.Column('mixed_count', sa.Integer(), nullable=True),
    sa.Column('neutral_count', sa.Integer(), nullable=True),
    sa.Column('total_mentions', sa.Integer(), nullable=True),
    sa.Column('mean_sentiment', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.bgg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'aspect')
    )
    op.create_table('review_aspects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('aspect', sa.String(), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.bgg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_aspects_aspect'), 'review_aspects', ['aspect'], unique=False)
    op.create_index(op.f('ix_review_aspects_game_id'), 'review_aspects', ['game_id'], unique=False)
    op.create_index(op.f('ix_review_aspects_review_id'), 'review_aspects', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_aspects_review_id'), table_name='review_aspects')
    op.drop_index(op.f('ix_review_aspects_game_id'), table_name='review_aspects')
    op.drop_index(op.f('ix_review_aspects_aspect'), table_name='review_aspects')
    op.drop_table('review_aspects')
    op.drop_table('game_aspect_aggregates')
    # ### end Alembic commands ###
