"""add_themes

Revision ID: f52e87b1f96c
Revises: 9fe753fc9003
Create Date: 2026-08-15 19:23:40.362922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52e87b1f96c'
down_revision: Union[str, Sequence[str], None] = '9fe753fc9003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_name'), 'themes', ['name'], unique=True)
    op.create_table('game_themes',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.bgg_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'theme_id')
    )
    op.create_index(op.f('ix_game_themes_theme_id'), 'game_themes', ['theme_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_themes_theme_id'), table_name='game_themes')
    op.drop_table('game_themes')
    op.drop_index(op.f('ix_themes_name'), table_name='themes')
    op.drop_table('themes')
    # ### end Alembic commands ###
