"""Add game_recommendations table

Revision ID: f7d3776dc81e
Revises: 2388b93dabc8
Create Date: 2026-08-15 16:04:10.605608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d3776dc81e'
down_revision: Union[str, Sequence[str], None] = '2388b93dabc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_recommendations',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('recommended_game_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.bgg_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_game_id'], ['games.bgg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'recommended_game_id', 'model')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_recommendations')
    # ### end Alembic commands ###
