"""Add constraints, indexes, and Artist entity

Revision ID: f998ed3df8b5
Revises: 00e27df745ad
Create Date: 2026-08-15 05:58:53.084824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f998ed3df8b5'
down_revision: Union[str, Sequence[str], None] = '00e27df745ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=True)
    op.create_table('game_artists',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.bgg_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'artist_id')
    )
    op.create_index(op.f('ix_game_artists_artist_id'), 'game_artists', ['artist_id'], unique=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('designers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_game_categories_category_id'), 'game_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_game_designers_designer_id'), 'game_designers', ['designer_id'], unique=False)
    op.create_index(op.f('ix_game_mechanics_mechanic_id'), 'game_mechanics', ['mechanic_id'], unique=False)
    op.create_index(op.f('ix_game_publishers_publisher_id'), 'game_publishers', ['publisher_id'], unique=False)
    op.alter_column('games', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mechanics', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('publishers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publishers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mechanics', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('games', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_game_publishers_publisher_id'), table_name='game_publishers')
    op.drop_index(op.f('ix_game_mechanics_mechanic_id'), table_name='game_mechanics')
    op.drop_index(op.f('ix_game_designers_designer_id'), table_name='game_designers')
    op.drop_index(op.f('ix_game_categories_category_id'), table_name='game_categories')
    op.alter_column('designers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_game_artists_artist_id'), table_name='game_artists')
    op.drop_table('game_artists')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
