"""categories instead of family

Revision ID: faa4df3d84fb
Revises: 875574550d3c
Create Date: 2026-08-15 03:32:14.682704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa4df3d84fb'
down_revision: Union[str, Sequence[str], None] = '875574550d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('categories', sa.String(), nullable=True))
    op.drop_column('games', 'family')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('family', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('games', 'categories')
    # ### end Alembic commands ###
